import {
  fetchCurrentSeasonCompetitions,
  fetchSeniorCompetition,
  fetchMatchSlots,
  fetchCompetitionInfo,
  fetchCompetitionMatches,
  fetchAllCompetitionMatches,
  fetchTeamStandings,
  fetchTeamStandingsUnofficial,
  fetchCompetitionGoalStats,
  fetchAllCompetitionScorers,
  fetchCompetitionRedCardStats,
  fetchCompetitionYellowCardStats,
  fetchAllCompetitionYellowCards,
  fetchAllCompetitionRedCards,
} from "./competitions.queries";

export const competitionsServerApi = {
  fetchCurrentSeasonCompetitions,
  fetchSeniorCompetition,
  fetchMatchSlots,
  fetchCompetitionInfo,
  fetchCompetitionMatches,
  fetchAllCompetitionMatches,
  fetchTeamStandings,
  fetchTeamStandingsUnofficial,
  fetchCompetitionGoalStats,
  fetchAllCompetitionScorers,
  fetchCompetitionRedCardStats,
  fetchCompetitionYellowCardStats,
  fetchAllCompetitionYellowCards,
  fetchAllCompetitionRedCards,
};
