/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    tenants: Tenant;
    news: News;
    media: Media;
    roster: Roster;
    equipment: Equipment;
    pages: Page;
    documents: Document;
    'board-members': BoardMember;
    'school-programs': SchoolProgram;
    'gallery-albums': GalleryAlbum;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    roster: RosterSelect<false> | RosterSelect<true>;
    equipment: EquipmentSelect<false> | EquipmentSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    'board-members': BoardMembersSelect<false> | BoardMembersSelect<true>;
    'school-programs': SchoolProgramsSelect<false> | SchoolProgramsSelect<true>;
    'gallery-albums': GalleryAlbumsSelect<false> | GalleryAlbumsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles: ('super-admin' | 'tenant-admin')[];
  tenants?:
    | {
        tenant: number | Tenant;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  displayName: string;
  /**
   * Tehnički identifikator kluba — ne mijenjati (razbija stranicu).
   */
  slug?: string | null;
  active?: boolean | null;
  /**
   * Rubrike koje klub koristi — određuje vidljivost kolekcija u adminu.
   */
  features?: ('pages' | 'documents' | 'board' | 'school' | 'gallery')[] | null;
  /**
   * Integracija s Hrvatskim nogometnim savezom (održava platforma).
   */
  hns?: {
    /**
     * Šalje se kao API_KEY header prema HNS-u. Skriveno od javnosti.
     */
    apiKey: string;
    /**
     * ID momčadi kluba u HNS sustavu.
     */
    teamId: string;
    /**
     * Dio naziva natjecanja koji identificira seniorsko natjecanje.
     */
    seniorCompetitionFilter?: string | null;
  };
  branding?: {
    shortName?: string | null;
    motto?: string | null;
    founded?: number | null;
    logo?: (number | null) | Media;
  };
  contact?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
    /**
     * Npr. "Popovača".
     */
    city?: string | null;
    /**
     * Npr. "Sisačko-moslavačka županija".
     */
    region?: string | null;
    /**
     * Link karte (src iz Google/OpenStreetMap <iframe> koda) za prikaz lokacije.
     */
    mapEmbedUrl?: string | null;
  };
  social?: {
    facebook?: string | null;
    youtube?: string | null;
    webshop?: string | null;
  };
  payment?: {
    iban?: string | null;
    recipient?: string | null;
    seasonTicketPrice?: number | null;
  };
  legal?: {
    /**
     * OIB udruge (11 znamenki).
     */
    oib?: string | null;
    /**
     * Broj u Registru udruga RH.
     */
    registryNumber?: string | null;
    /**
     * Npr. "Ured državne uprave u Sisačko-moslavačkoj županiji".
     */
    registryAuthority?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Ostavi prazno — automatski se popuni iz naziva datoteke.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  /**
   * Auto-generira se iz naziva ako ostaviš prazno.
   */
  slug?: string | null;
  publishedAt?: string | null;
  thumbnail?: (number | null) | Media;
  /**
   * Kratki sažetak za kartice. Ako ostaviš prazno, generira se iz teksta.
   */
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roster".
 */
export interface Roster {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Pretraži igrača po imenu — odabir automatski popuni ime. Odaberi prije spremanja.
   */
  personId: number;
  /**
   * Ime koje se prikazuje na stranici (puno ime ili nadimak).
   */
  displayName: string;
  position: 'vratar' | 'obrambeni' | 'vezni' | 'napadac' | 'trener';
  /**
   * Redoslijed unutar pozicije (manji broj se prikazuje prvi).
   */
  displayOrder?: number | null;
  jerseyNumber?: number | null;
  captain?: boolean | null;
  /**
   * Fotografija igrača.
   */
  photo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipment".
 */
export interface Equipment {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Naziv proizvoda prikazan na kartici (npr. "Dres domaći", "Polaris jakna").
   */
  displayName: string;
  category: 'paketi' | 'dresovi' | 'trenirke' | 'jakne' | 'dodaci';
  price: number;
  /**
   * Sliku uploadaj u galeriju i ovdje je odaberi.
   */
  image?: (number | null) | Media;
  /**
   * Direktan link na proizvod u web trgovini (mora počinjati s http:// ili https://).
   */
  externalUrl: string;
  /**
   * Redoslijed unutar kategorije (manji broj se prikazuje prvi).
   */
  displayOrder?: number | null;
  /**
   * Prikaži proizvod u carouselu na naslovnici.
   */
  featured?: boolean | null;
  /**
   * Isključi da sakriješ proizvod bez brisanja.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Kojoj rubrici ovaj sadržaj pripada (jedan zapis po rubrici).
   */
  key: 'povijest' | 'navijaci' | 'statut' | 'skola-info' | 'seniori-info';
  /**
   * Glavni naslov stranice.
   */
  title: string;
  /**
   * Mali nadnaslov iznad glavnog naslova (opcionalno).
   */
  eyebrow?: string | null;
  /**
   * Naslovna slika rubrike (opcionalno).
   */
  heroImage?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Dodatne fotografije prikazane uz tekst (opcionalno).
   */
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Kratki opis za Google (meta description).
   */
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Naziv prikazan na stranici.
   */
  title: string;
  category: 'statut' | 'pravilnik' | 'obrazac' | 'izvjesce' | 'ostalo';
  /**
   * Redoslijed unutar kategorije (manji broj prvi).
   */
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "board-members".
 */
export interface BoardMember {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  /**
   * Npr. "Predsjednik", "Tajnik", "Trener vratara".
   */
  role: string;
  /**
   * Sekcija u kojoj se član prikazuje.
   */
  roleGroup: 'predsjednistvo' | 'nadzorni-odbor' | 'strucni-stozer' | 'ostalo';
  /**
   * Fotografija člana (opcionalno).
   */
  photo?: (number | null) | Media;
  email?: string | null;
  phone?: string | null;
  /**
   * Redoslijed unutar sekcije (manji broj prvi).
   */
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "school-programs".
 */
export interface SchoolProgram {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Naziv skupine/programa (npr. "Limači U7–U9").
   */
  name: string;
  /**
   * Npr. "U7–U9", "7–9 godina".
   */
  ageRange?: string | null;
  /**
   * Ime trenera (opcionalno).
   */
  coach?: string | null;
  /**
   * Npr. "Pon, Sri, Pet — 17:00–18:30".
   */
  schedule?: string | null;
  /**
   * Prikazuje se na kartici i kao glavni tekst ("O programu") na stranici programa.
   */
  description?: string | null;
  photo?: (number | null) | Media;
  /**
   * Redoslijed prikaza (manji broj prvi).
   */
  displayOrder?: number | null;
  /**
   * Isključi da sakriješ program bez brisanja.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-albums".
 */
export interface GalleryAlbum {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  /**
   * Auto-generira se iz naziva ako ostaviš prazno.
   */
  slug?: string | null;
  date?: string | null;
  /**
   * Naslovna slika albuma.
   */
  coverImage?: (number | null) | Media;
  description?: string | null;
  photos?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Redoslijed prikaza albuma (manji broj prvi).
   */
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'roster';
        value: number | Roster;
      } | null)
    | ({
        relationTo: 'equipment';
        value: number | Equipment;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'board-members';
        value: number | BoardMember;
      } | null)
    | ({
        relationTo: 'school-programs';
        value: number | SchoolProgram;
      } | null)
    | ({
        relationTo: 'gallery-albums';
        value: number | GalleryAlbum;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  displayName?: T;
  slug?: T;
  active?: T;
  features?: T;
  hns?:
    | T
    | {
        apiKey?: T;
        teamId?: T;
        seniorCompetitionFilter?: T;
      };
  branding?:
    | T
    | {
        shortName?: T;
        motto?: T;
        founded?: T;
        logo?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
        city?: T;
        region?: T;
        mapEmbedUrl?: T;
      };
  social?:
    | T
    | {
        facebook?: T;
        youtube?: T;
        webshop?: T;
      };
  payment?:
    | T
    | {
        iban?: T;
        recipient?: T;
        seasonTicketPrice?: T;
      };
  legal?:
    | T
    | {
        oib?: T;
        registryNumber?: T;
        registryAuthority?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  publishedAt?: T;
  thumbnail?: T;
  excerpt?: T;
  content?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roster_select".
 */
export interface RosterSelect<T extends boolean = true> {
  tenant?: T;
  personId?: T;
  displayName?: T;
  position?: T;
  displayOrder?: T;
  jerseyNumber?: T;
  captain?: T;
  photo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipment_select".
 */
export interface EquipmentSelect<T extends boolean = true> {
  tenant?: T;
  displayName?: T;
  category?: T;
  price?: T;
  image?: T;
  externalUrl?: T;
  displayOrder?: T;
  featured?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  tenant?: T;
  key?: T;
  title?: T;
  eyebrow?: T;
  heroImage?: T;
  content?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  category?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "board-members_select".
 */
export interface BoardMembersSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  role?: T;
  roleGroup?: T;
  photo?: T;
  email?: T;
  phone?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "school-programs_select".
 */
export interface SchoolProgramsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  ageRange?: T;
  coach?: T;
  schedule?: T;
  description?: T;
  photo?: T;
  displayOrder?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-albums_select".
 */
export interface GalleryAlbumsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  date?: T;
  coverImage?: T;
  description?: T;
  photos?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}